### ISSUE TITLE
Issues with starting Training

### ISSUE THREAD

**Issue by sree3333** [ternaus/cloths_segmentation#7]
I have set up all the required data and the paths but still get this error all the configs

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/electron/cloths_segmentation/cloths_segmentation/train.py", line 189, in <module>
    main()
  File "/home/electron/cloths_segmentation/cloths_segmentation/train.py", line 175, in main
    pipeline = SegmentPeople(hparams)
  File "/home/electron/cloths_segmentation/cloths_segmentation/train.py", line 46, in __init__
    state_dict = state_dict_from_disk(
  File "/home/electron/.local/lib/python3.9/site-packages/iglovikov_helper_functions/dl/pytorch/utils.py", line 32, in state_dict_from_disk
    checkpoint = torch.load(file_path, map_location=lambda storage, loc: storage)
  File "/home/electron/.local/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/electron/.local/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/electron/.local/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '2020-10-29/epoch=4.ckpt'

**Comment by sree3333** [comment]
@ternaus I think there is some problem with config file, they are the reason for issues in training please could you check and let me know. I have made a datasets for the repo with high quality images of nearly 10k images. but unable to train due to problems in the repo
